version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: "Sales of Greenwez"

        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count: 90, period: day }
        
        columns:
          - name: date_date
            description: "Date of purchase"
          - name: orders_id
            description: "Unique order identifier"
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id )"

      - name: product
        identifier: raw_gz_product
        description: "Product data of Greenwez"

      - name: ship
        identifier: raw_gz_ship
        description: "Shipping data of Greenwez"

      - name: ads_adwords
        identifier: raw_gz_adwords
        description: "Ads with Adwords"

      - name: ads_bing
        identifier: raw_gz_bing
        description: "Ads with Bing"

      - name: ads_criteo
        identifier: raw_gz_criteo
        description: "Ads with Criteo"

      - name: ads_facebook
        identifier: raw_gz_facebook
        description: "Ads with Facebook"

models:
  - name: int_orders_margin
    description: calculates margin
    columns:
      - name: orders_id
        tests:
          - unique
          - not_null
  - name: finance_days
    description: final table